services:
  db:
    image: mysql:latest
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "mypass"
    volumes: 
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
